In [4]:
import pandas as pd

In [7]:
df = pd.read_csv(r'C:\Users\Asus\OneDrive\Documents\zohra shaikh\pandas\Data Launch Analysis\mission_launches.csv')

In [21]:
df = df.drop(columns=['Unnamed: 0.1' , 'Unnamed: 0'], errors='ignore')

In [22]:
df.head()

,Organisation,Location,Date,Detail,Rocket_Status,Price,Mission_Status
0,SpaceX,"LC-39A, Kennedy Space Center, Florida, USA",2020-08-07 05:12:00+00:00,Falcon 9 Block 5 | Starlink V1 L9 & BlackSky,StatusActive,50.00,Success
1,CASC,"Site 9401 (SLS-2), Jiuquan Satellite Launch Ce...",2020-08-06 04:01:00+00:00,Long March 2D | Gaofen-9 04 & Q-SAT,StatusActive,29.75,Success
2,SpaceX,"Pad A, Boca Chica, Texas, USA",2020-08-04 23:57:00+00:00,Starship Prototype | 150 Meter Hop,StatusActive,NaN,Success
3,Roscosmos,"Site 200/39, Baikonur Cosmodrome, Kazakhstan",2020-07-30 21:25:00+00:00,Proton-M/Briz-M | Ekspress-80 & Ekspress-103,StatusActive,65.00,Success
4,ULA,"SLC-41, Cape Canaveral AFS, Florida, USA",2020-07-30 11:50:00+00:00,Atlas V 541 | Perseverance,StatusActive,145.00,Success

In [33]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4324 entries, 0 to 4323
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Organisation    4324 non-null   str
 1   Location        4324 non-null   str
 2   Date            4324 non-null   str
 3   Detail          4324 non-null   str
 4   Rocket_Status   4324 non-null   str
 5   Price           964 non-null    str
 6   Mission_Status  4324 non-null   str
dtypes: str(7)
memory usage: 763.0 KB

In [13]:
# Converting Price to float and Date to datetime
df['Price'] = pd.to_numeric(df['Price'], errors='coerce')
df['Date'] = pd.to_datetime(df['Date'], errors='coerce')

In [15]:
# Which organisation conducted the most launches
df['Organisation'].value_counts()

Organisation
RVSN USSR           1777
Arianespace          279
CASC                 251
General Dynamics     251
NASA                 203
VKS RF               201
US Air Force         161
ULA                  140
Boeing               136
Martin Marietta      114
SpaceX               100
MHI                   84
Northrop              83
Lockheed              79
ISRO                  76
Roscosmos             55
ILS                   46
Sea Launch            36
ISAS                  30
Kosmotras             22
US Navy               17
Rocket Lab            13
ISA                   13
Eurockot              13
ESA                   13
Blue Origin           12
IAI                   11
ExPace                10
ASI                    9
CNES                   8
AMBA                   8
JAXA                   7
Land Launch            7
MITT                   7
CASIC                  5
KCST                   5
UT                     5
Exos                   4
CECLES                 4
Arm??e de l'Air        4
KARI                   3
SRC                    3
AEB                    3
Yuzhmash               2
RAE                    2
OKB-586                2
Virgin Orbit           1
IRGC                   1
i-Space                1
OneSpace               1
Landspace              1
Sandia                 1
Khrunichev             1
Starsem                1
EER                    1
Douglas                1
Name: count, dtype: int64

In [23]:
# How many missions were successful vs unsuccessful?
df['Mission_Status'].value_counts()

Mission_Status
Success              3879
Failure               339
Partial Failure       102
Prelaunch Failure       4
Name: count, dtype: int64

In [35]:
df['Year'] = df['Date'].dt.year.astype('Int64')

# How did the number of launches changed over years
launch_yearwise = df['Year'].value_counts().sort_index()
launch_yearwise

Year
1957      3
1958     22
1959     20
1960     38
1961     52
       ...
2016     88
2017     90
2018    117
2019    107
2020     63
Name: count, Length: 64, dtype: Int64

In [41]:
# Which organisation have the highest number of succesful missions
successful_launches = df.loc[df['Mission_Status'] == 'Success'].value_counts('Organisation')
successful_launches

Organisation
RVSN USSR           1614
Arianespace          269
CASC                 231
General Dynamics     203
VKS RF               188
NASA                 186
ULA                  139
Boeing               131
US Air Force         129
Martin Marietta      100
SpaceX                94
MHI                   80
Northrop              74
Lockheed              74
ISRO                  63
Roscosmos             51
ILS                   45
Sea Launch            33
ISAS                  26
Kosmotras             21
Blue Origin           12
Eurockot              12
Rocket Lab            11
IAI                    9
ExPace                 9
ESA                    9
ASI                    9
JAXA                   6
Land Launch            6
MITT                   6
CNES                   6
ISA                    4
AMBA                   4
CASIC                  3
Arm??e de l'Air        3
KCST                   2
SRC                    2
Yuzhmash               2
OKB-586                2
US Navy                2
IRGC                   1
i-Space                1
Khrunichev             1
KARI                   1
Starsem                1
Douglas                1
RAE                    1
UT                     1
CECLES                 1
Name: count, dtype: int64

In [48]:
# Which launches location are used most?
launches_location = df['Location'].value_counts()
launches_location

Location
Site 31/6, Baikonur Cosmodrome, Kazakhstan        235
Site 132/1, Plesetsk Cosmodrome, Russia           216
Site 43/4, Plesetsk Cosmodrome, Russia            202
Site 41/1, Plesetsk Cosmodrome, Russia            198
Site 1/5, Baikonur Cosmodrome, Kazakhstan         193
                                                 ...
Site 250, Baikonur Cosmodrome, Kazakhstan           1
LC-576A1, Vandenberg AFB, California, USA           1
Santa Rita 2, San Marco Launch Platform, Kenya      1
LC-18B, Cape Canaveral AFS, Florida, USA            1
LC-11, Cape Canaveral AFS, Florida, USA             1
Name: count, Length: 137, dtype: int64

In [64]:
# Calculate overall average launch cost
avg_cost = df['Price'].mean()
print("Average overall cost: ", avg_cost)

# Calculate average cost per organisation and sort from highest to lowest
avg_org_cost = df.groupby('Organisation')['Price'].mean()
highest_avg_cost = avg_org_cost.dropna().sort_values(ascending=False)
highest_avg_cost

Average overall cost:  129.79523709167546

Organisation
NASA               450.000000
Boeing             177.285714
Arianespace        170.260417
ULA                151.000000
ILS                101.538462
MHI                 95.472973
Martin Marietta     80.155556
US Air Force        59.650769
JAXA                56.000000
SpaceX              54.989899
Roscosmos           51.630435
Northrop            47.349398
VKS RF              46.936364
Eurockot            41.800000
CASC                40.128228
ESA                 37.000000
Lockheed            35.000000
ISRO                32.492537
Kosmotras           29.000000
ExPace              28.300000
EER                 20.000000
Sandia              15.000000
Virgin Orbit        12.000000
Rocket Lab           7.500000
Name: Price, dtype: float64

In [102]:
# Does launch cost appear to differ between successful and failed missions
status_diff_cost = df.groupby(['Organisation', 'Mission_Status'])['Price'].mean().unstack()
status_diff_cost

Mission_Status       Failure  Partial Failure  Prelaunch Failure     Success
Organisation
AEB                      NaN              NaN                NaN         NaN
AMBA                     NaN              NaN                NaN         NaN
ASI                      NaN              NaN                NaN         NaN
Arianespace       118.500000       200.000000                NaN  171.053763
Arm??e de l'Air          NaN              NaN                NaN         NaN
Blue Origin              NaN              NaN                NaN         NaN
Boeing                   NaN       350.000000                NaN  148.500000
CASC               52.836667        42.866667                NaN   39.823355
CASIC                    NaN              NaN                NaN         NaN
CECLES                   NaN              NaN                NaN         NaN
CNES                     NaN              NaN                NaN         NaN
Douglas                  NaN              NaN                NaN         NaN
EER                20.000000              NaN                NaN         NaN
ESA                      NaN              NaN                NaN   37.000000
Eurockot           41.800000              NaN                NaN   41.800000
ExPace             28.300000              NaN                NaN         NaN
Exos                     NaN              NaN                NaN         NaN
General Dynamics         NaN              NaN                NaN         NaN
IAI                      NaN              NaN                NaN         NaN
ILS                      NaN              NaN                NaN  101.538462
IRGC                     NaN              NaN                NaN         NaN
ISA                      NaN              NaN                NaN         NaN
ISAS                     NaN              NaN                NaN         NaN
ISRO               39.400000        39.666667                NaN   31.542373
JAXA                     NaN              NaN                NaN   56.000000
KARI                     NaN              NaN                NaN         NaN
KCST                     NaN              NaN                NaN         NaN
Khrunichev               NaN              NaN                NaN         NaN
Kosmotras          29.000000              NaN                NaN   29.000000
Land Launch              NaN              NaN                NaN         NaN
Landspace                NaN              NaN                NaN         NaN
Lockheed                 NaN              NaN                NaN   35.000000
MHI                      NaN              NaN                NaN   95.472973
MITT                     NaN              NaN                NaN         NaN
Martin Marietta    85.800000              NaN                NaN   78.542857
NASA              450.000000              NaN                NaN  450.000000
Northrop           47.857143        40.000000                NaN   47.500000
OKB-586                  NaN              NaN                NaN         NaN
OneSpace                 NaN              NaN                NaN         NaN
RAE                      NaN              NaN                NaN         NaN
RVSN USSR                NaN              NaN                NaN         NaN
Rocket Lab          7.500000              NaN                NaN    7.500000
Roscosmos                NaN        48.500000                NaN   51.772727
SRC                      NaN              NaN                NaN         NaN
Sandia             15.000000              NaN                NaN         NaN
Sea Launch               NaN              NaN                NaN         NaN
SpaceX             19.375000        59.500000               62.0   56.397849
Starsem                  NaN              NaN                NaN         NaN
ULA                      NaN       109.000000                NaN  151.432990
US Air Force       61.115000        59.000000                NaN   59.551739
US Navy                  NaN              NaN                NaN         NaN
UT                       NaN              NaN                NaN         NaN
VKS RF             65.000000        41.800000                NaN   46.676667
Virgin Orbit       12.000000              NaN                NaN         NaN
Yuzhmash                 NaN              NaN                NaN         NaN
i-Space                  NaN              NaN                NaN         NaN

In [99]:
# Which organisations have the best success rate
df['is_success'] = df['Mission_Status'] == 'Success'
success_rate = df.groupby('Organisation')['is_success'].mean() * 100
success_rate

Organisation
AEB                   0.000000
AMBA                 50.000000
ASI                 100.000000
Arianespace          96.415771
Arm??e de l'Air      75.000000
Blue Origin         100.000000
Boeing               96.323529
CASC                 92.031873
CASIC                60.000000
CECLES               25.000000
CNES                 75.000000
Douglas             100.000000
EER                   0.000000
ESA                  69.230769
Eurockot             92.307692
ExPace               90.000000
Exos                  0.000000
General Dynamics     80.876494
IAI                  81.818182
ILS                  97.826087
IRGC                100.000000
ISA                  30.769231
ISAS                 86.666667
ISRO                 82.894737
JAXA                 85.714286
KARI                 33.333333
KCST                 40.000000
Khrunichev          100.000000
Kosmotras            95.454545
Land Launch          85.714286
Landspace             0.000000
Lockheed             93.670886
MHI                  95.238095
MITT                 85.714286
Martin Marietta      87.719298
NASA                 91.625616
Northrop             89.156627
OKB-586             100.000000
OneSpace              0.000000
RAE                  50.000000
RVSN USSR            90.827237
Rocket Lab           84.615385
Roscosmos            92.727273
SRC                  66.666667
Sandia                0.000000
Sea Launch           91.666667
SpaceX               94.000000
Starsem             100.000000
ULA                  99.285714
US Air Force         80.124224
US Navy              11.764706
UT                   20.000000
VKS RF               93.532338
Virgin Orbit          0.000000
Yuzhmash            100.000000
i-Space             100.000000
Name: is_success, dtype: float64